polishing
Signed-off-by: Scott Andrews <scott@andrews.me>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -82,30 +82,32 @@ runs:
           echo "${tools}"
           
           # find exact match
-          while IFS= read -r item ; do
+          for item in "${tools}" ; do
             if [[ "${item}" == "${tool}" ]] ; then
-              if [[ "${package}" != "" ]] ; then
+              if [[ "${normalized_module}" != "" ]] ; then
                 echo "::error title=Duplicate tool::tool \"${tool}\" found twice in go.mod"
                 exit 1
               fi
               echo "Found tool: ${item}"
-              package="${item}"
+              normalized_module="${item}"
             fi
-          done <<< "${tools}"
+          done
 
           # find shorthand match
-          while IFS= read -r item ; do
-            if [[ "${item}" == "*/${tool}" ]] ; then
-              if [[ "${package}" != "" ]] ; then
-                echo "::error title=Ambiguous tool::tool \"${tool}\" found twice in go.mod"
-                exit 1
+          if [[ "${normalized_module}" == "" ]] ; then
+            for item in "${tools}" ; do
+              if [[ "${item}" == "*/${tool}" ]] ; then
+                if [[ "${normalized_module}" != "" ]] ; then
+                  echo "::error title=Ambiguous tool::tool \"${tool}\" found twice in go.mod"
+                  exit 1
+                fi
+                echo "Found tool: ${tool} -> ${item}"
+                normalized_module="${item}"
               fi
-              echo "Found tool: ${tool} -> ${item}"
-              package="${item}"
-            fi
-          done <<< "${tools}"
+            done
+          fi
 
-          if [[ "${package}" == "" ]] ; then
+          if [[ "${normalized_module}" == "" ]] ; then
             echo "::error title=Tool not defined::tool \"${tool}\" not found in go.mod"
             exit 1
           fi
