streamline provenance check
Signed-off-by: Scott Andrews <scott@andrews.me>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -44,10 +44,12 @@ jobs:
         - package: sigs.k8s.io/kind
           version: latest
           binary-url-template: https://github.com/kubernetes-sigs/kind/releases/download/${version}/kind-${os}-${arch}
+          expect-provenance: download
         - package: github.com/google/go-containerregistry/cmd/crane
           version: v0.21.7
           binary-url-template: https://github.com/google/go-containerregistry/releases/download/${version}/go-containerregistry_${os^}_${arch/amd64/x86_64}.tar.gz
           binary-path-within-archive: crane
+          expect-provenance: download
     runs-on: ${{ matrix.os || 'ubuntu-latest' }}
     steps:
     - uses: actions/checkout@v6
@@ -108,20 +110,12 @@ jobs:
       run: |
         set -euo pipefail
 
-        cache_enabled="${{ matrix.cache-enabled }}"
-        cache_enabled="${cache_enabled:-true}"
         provenance="${{ steps.install.outputs.provenance }}"
+        expect_provenance="${{ matrix.expect-provenance || case(matrix.cache-enabled, 'cache', 'source') }}"
 
-        echo "cache-enabled = ${cache_enabled}"
         echo "artifact-provenance = ${provenance}"
 
-        if [[ "${provenance}" != "download" ]] ; then
-          if [[ "${cache_enabled}" == "true" && "${provenance}" != "cache" ]] ; then
-            echo "::error title=Expected cache::artifact from ${provenance}, expected to be from cache"
-            exit 1
-          fi
-          if [[ "${cache_enabled}" != "true" && "${provenance}" != "source" ]] ; then
-            echo "::error title=Expected source::artifact from ${provenance}, expected to be from source"
-            exit 1
-          fi
+        if [[ "${expect_provenance}" != "${provenance}" ]] ; then
+          echo "::error title=Expected provenance::artifact from ${provenance}, expected to be from ${expect_provenance}"
+          exit 1
         fi
